// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSaludMigrantes.Models;

#nullable disable

namespace SaludMigrantes.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoSaludMigrantes.Models.Localidad", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id");

                    b.ToTable("LOCALIDAD", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Nombre = "01. USAQUÉN"
                        },
                        new
                        {
                            Id = 2L,
                            Nombre = "02. CHAPINERO"
                        },
                        new
                        {
                            Id = 3L,
                            Nombre = "03. SANTA FE"
                        },
                        new
                        {
                            Id = 4L,
                            Nombre = "04. SAN CRISTOBAL"
                        },
                        new
                        {
                            Id = 5L,
                            Nombre = "05. USME"
                        },
                        new
                        {
                            Id = 6L,
                            Nombre = "06. TUNJUELITO"
                        },
                        new
                        {
                            Id = 7L,
                            Nombre = "07. BOSA"
                        },
                        new
                        {
                            Id = 8L,
                            Nombre = "08. KENNEDY"
                        },
                        new
                        {
                            Id = 9L,
                            Nombre = "09. FONTIBÓN"
                        },
                        new
                        {
                            Id = 10L,
                            Nombre = "10. ENGATIVÁ"
                        },
                        new
                        {
                            Id = 11L,
                            Nombre = "11. SUBA"
                        },
                        new
                        {
                            Id = 12L,
                            Nombre = "12. BARRIOS UNIDOS"
                        },
                        new
                        {
                            Id = 13L,
                            Nombre = "13. TEUSAQUILLO"
                        },
                        new
                        {
                            Id = 14L,
                            Nombre = "14. MÁRTIRES"
                        },
                        new
                        {
                            Id = 15L,
                            Nombre = "15. ANTONIO NARIÑO"
                        },
                        new
                        {
                            Id = 16L,
                            Nombre = "16. PUENTE ARANDA"
                        },
                        new
                        {
                            Id = 17L,
                            Nombre = "17. CANDELARIA"
                        },
                        new
                        {
                            Id = 18L,
                            Nombre = "18. RAFAEL URIBE"
                        },
                        new
                        {
                            Id = 19L,
                            Nombre = "19. CIUDAD BOLIVAR"
                        },
                        new
                        {
                            Id = 29L,
                            Nombre = "20. SUMAPAZ"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
